apiVersion: catalog.cattle.io/v1
kind: UIPlugin
metadata:
  name: {{ include "extension-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "extension-server.labels" . | nindent 4 }}
spec:
  plugin:
    name: {{ include "extension-server.fullname" . }}
    version: {{ (semver (default .Chart.AppVersion .Values.plugin.versionOverride)).Original }}
    endpoint: https://raw.githubusercontent.com/rancher/partner-extensions/main/extensions/nutanix/1.1.3
    compressedEndpoint: {{ .Values.plugin.compressedEndpoint | quote }}
    noCache: {{ .Values.plugin.noCache }}
    noAuth: {{ .Values.plugin.noAuth }}
    metadata: {{ include "extension-server.pluginMetadata" . | indent 6 }}