annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/namespace: cattle-ui-plugin-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux, windows
  catalog.cattle.io/scope: management
  catalog.cattle.io/ui-component: plugins
  catalog.cattle.io/kube-version: '>= 1.16.0-0'
  catalog.cattle.io/rancher-version: '>= 2.13.1-0 || >= 2.12.5-0 < 2.13.0-0 || >= 2.11.8-0 < 2.12.0-0'
  catalog.cattle.io/ui-extensions-version: '>= 3.0.0 < 4.0.0'
apiVersion: v2
appVersion: 1.1.3
description: >-
  Nutanix UI Extension provides a seamless interface for configuring Rancher
  clusters on Nutanix Cloud Platform
name: nutanix
type: application
version: 1.1.3
icon: https://raw.githubusercontent.com/rancher/partner-extensions/main/icons/nutanix/1.1.3-icon-nutanix.svg
