nameOverride: ""
fullnameOverride: ""
plugin:
  enabled: true
  versionOverride: ""
  endpoint: >-
    https://raw.githubusercontent.com/nutanix-cloud-native/nutanix-rancher-extension/gh-pages/extensions/nutanix/1.1.3
  compressedEndpoint: >-
    https://raw.githubusercontent.com/nutanix-cloud-native/nutanix-rancher-extension/gh-pages/extensions/nutanix/1.1.3.tgz
  noCache: false
  noAuth: false
  metadata:
    catalog.cattle.io/kube-version: ">= 1.16.0-0"
    catalog.cattle.io/rancher-version: ">= 2.13.1-0 || >= 2.12.5-0 < 2.13.0-0 || >= 2.11.8-0 < 2.12.0-0"
    catalog.cattle.io/ui-extensions-version: ">= 3.0.0 < 4.0.0"
